# Generated by Django 5.1.2 on 2024-10-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
